# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weight',
            options={'verbose_name': 'Weight', 'verbose_name_plural': 'Weights'},
        ),
    ]
