# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('email', models.EmailField(max_length=75, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=75, verbose_name='Telephone')),
                ('bio', models.TextField()),
                ('tag_line', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('google_plus', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='printers_logos/')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printers_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printers',
            },
        ),
    ]
