# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printer',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='google_plus',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='printers_logos/'),
        ),
        migrations.AddField(
            model_name='printer',
            name='tag_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
